### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by umairchauhan1** [sonnenglas/amazon-mws-laravel#54]
when i want to install the package following error occur. 
_**Problem 1
    - Installation request for sonnenglas/laravel5-amazon-mws ^4.1 -> satisfiable by sonnenglas/laravel5-amazon-mws[4.1.0].
    - Conclusion: remove laravel/framework v7.28.4
    - Conclusion: don't install laravel/framework v7.28.4**_
any solution for this.

**Comment by przemekperon** [comment]
The package was not compatible with Laravel 7 in November 2020. It is now (version `5.0.0` or higher)
